# This is an example configuration for Docker Compose. Make sure to atleast update
# the cookie secret & postgres database password.
#
# Some other recommendations:
# 1. To persist Postgres data, assign it a volume host location.

# 2. Split the worker service to   adhoc workers and scheduled queries workers.
# 将adhoc和scheduled quries worker 最好放到两个服务里

###############################################

# 这里温习一些linux的命令和文件系统

#curl -L https://github.com/docker/compose/releases/download/1.8.0/run.sh > /usr/local/bin/docker-compose

# > 如果没有这个文件，将创建

# -L location (HTTP/HTTPS)如果服务器报告说请求页面已经转移到其他地址了（头部Location:会表明，和 3XX响应码），这个选项将会让curl重做请求到新的位置


#/bin  存放所有用户皆可用的系统程序，系统启动或者系统修复时可用（在没有挂载 /usr 目录时就可以使用）
#/sbin 存放超级用户才能使用的系统程序
#/usr/bin 存放所有用户都可用的应用程序
#/usr/sbin 存放超级用户才能使用的应用程序

#/usr/local/bin 存放所有用户都可用的与本地机器无关的程序
#/usr/local/sbin 存放超级用户才能使用的与本地机器无关的程序


#/usr/bin 存放所有用户都可用的应用程序
#/usr/local/bin 存放所有用户都可用的与本地机器无关的程序


###############################################

#YAML语法
#http://www.ruanyifeng.com/blog/2016/07/yaml.html

#: 表示key-value
#缩进表示层级
#- 表示数组


###############################################


#Docker-compose 就是对多个容器的编排管理，
#比如 docker-compse build ，
#等效于对project下的每一个service的images，执行docker  run xxxxxx
#使得对多个容器的管理更便捷

###############################################
#docker-compose的命令
#https://yeasy.gitbooks.io/docker_practice/compose/commands.html


###############################################
#compose 中的重要概念

#项目 (project)：由一组关联的应用容器组成的一个完整业务单元，在 docker-compose.yml 文件中定义。

#服务 (service)：一个应用的容器，实际上可以包括若干运行相同镜像的容器实例。

#只要所操作的平台支持 Docker API，就可以在其上利用 Compose 来进行编排管理。

###############################################

version: '2'
services:


###############################################
#5个容器

# Web service
  server:
    image: redash/redash:latest


###############################################

#两种方式，一种根据Dockerfile文件build，一种现成的image

# image 指令指定镜像或 build 指令（需要 Dockerfile）等来自动构建生成镜像。
#
#如果使用 build 指令，在 Dockerfile 中设置的选项(例如：CMD, EXPOSE, VOLUME, ENV 等) 将会自动被获取，无需在 docker-compose.yml 中再次设置。

#    build:
#      context: ./dir
#      dockerfile: Dockerfile-alternate
#      args:
#        buildno: 1

###############################################
    # gunicorn 命令, docker-entrypoint定义的
    #一般Dockerfile文件会有个CMD，这个会覆盖掉
    #覆盖容器启动后默认执行的命令,

    command: server

###############################################################
###为什么没有worker和Nginx
    depends_on:
#    解决容器的依赖、启动先后的问题, postgres先启动，redis再启动
      - postgres
      - redis

###############################################################
    ports:
      - "5000:5000"
    environment:
   # 电脑shell的环境变量

#   !!!!!!!!!!!!!!!!!!!!!!!!!!
#  如果变量名称或者值中用到 true|false，yes|no 等表达 布尔 含义的词汇，最好放到引号里，避免 YAML 自动解析某些内容为对应的布尔语义。这些特定词汇，包括
#y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF
#   还有
#注意：当使用 HOST:CONTAINER 格式来映射端口时，如果你使用的容器端口小于 60 并且没放到引号里，可能会得到错误结果，因为 YAML 会自动解析 xx:yy 这种数字格式为 60 进制。为避免出现这种问题，建议数字串都采用引号包括起来的字符串格式。



      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4

    restart: always


# 任务队列，消息队列, 这个配置相对复杂些
  worker:

    image: redash/redash:latest

    # celery 命令, docker-entrypoint定义的
    command: scheduler

    environment:

      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2

    restart: always

# Cache
  redis:
    image: redis:3.0-alpine
    restart: always

# Sql
  postgres:
    image: postgres:9.5.6-alpine


########################数据库本地存储############################
    volumes:
    # HOST:CONTAINER:ro
    # 两个文件夹
       - /opt/postgres-data:/var/lib/postgresql/data
    restart: always


# Web server

  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"


############???????????????????????#############
    depends_on:
      - server

# links
#注意：不推荐使用该指令。

#https://stackoverflow.com/questions/35832095/difference-between-links-and-depends-on-in-docker-compose-yml

# ngnix容器 总是连接 server服务，即使server使用了-P,每次生成的container的port都不一样
# 但是我们在具体的项目中，不建议使用-P,随机端口
# 我们不推荐使用这个命令

    links:
      - server





############???????????????????????#############
    restart: always
